export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';

export const ADD_POLL = 'ADD_POLL';
export const CHANGE_SELECTED_POLL = 'CHANGE_SELECTED_POLL';
export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST';
export const ADD_POLLS = 'ADD_POLLS';
export const ADD_SELECTED_POLL = 'ADD_SELECTED_POLL';
export const DELETE_POLL = 'DELETE_POLL';
