export const ADD_POLL = 'ADD_POLL';
export const CHANGE_SELECTED_POLL = 'CHANGE_SELECTED_POLL';
export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST';
export const ADD_POLLS = 'ADD_POLLS';
export const ADD_SELECTED_POLL = 'ADD_SELECTED_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const SHOW_MODAL = 'SHOW_MODAL';
