export const ADD_POLL = 'ADD_POLL';
export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST';
export const ADD_POLLS = 'ADD_POLLS';
export const ADD_SELECTED_POLL = 'ADD_SELECTED_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const VOTE = 'VOTE';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FALIURE = 'LOGIN_FALIURE';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FALIURE = 'LOGOUT_FALIURE';

export const REQUEST_CHECK_TOKEN = 'REQUEST_CHECK_TOKEN';
export const TOKEN_VALID = 'TOKEN_VALID';
export const TOKEN_INVALID = 'TOKEN_INVALID';
